### ISSUE TITLE
Flatpack version fails to be confined in a custom directory

### ISSUE THREAD

**Issue by nidamanx** [flathub/org.qownnotes.QOwnNotes#15]
Hi,
I submitted this [issue](https://github.com/pbek/QOwnNotes/issues/2055#issuecomment-780608281) to the QOwnNotes git.
Dev said you are the one who can solve/explain.
Thanks

**Comment by stobbsm** [comment]
The home directory is what it is given access to. Shouldn't have access to the entire filesystem.

Home was chosen to be able to save to custom locations, and ensure it could store its files in the nextcloud sync directory.

**Comment by nidamanx** [comment]
Well, As you say, /home is open by default.
I understand you point because it's easy to config for many people, but I cannot override those settings.
I tried again, just now, and I can import/export files from everywhere in my OS. 
I tried /srv and /etc and few more. I didn't try all, but even only /etc is too much.
Is there a way to lock the App out of those directories?
Thanks

**Comment by Erick555** [comment]
try `flatpak run org.qownnotes.QOwnNotes --nofilesystem=home --filesystem=~/Note
`.

The fact you can import/export files anywhere doesn't mean app itself can access those files - this is working through xdg-desktop-portal which needs user action and can't be trigerred automatically.

**Comment by nidamanx** [comment]
I tested `flatpak run org.qownnotes.QOwnNotes --nofilesystem=home --filesystem=~/Note`
Same result, Access everywhere /home /dev /usr/ /boot /run and more
It really seems that settings cannot be overridden by the user

Just to have an example, I also tested Skype and it's perfectly isolated
I used the very good FlatSeal and command line with same good results.

I need to search/inform more about:
>The fact you can import/export files anywhere doesn't mean app itself can access those files - this is working through xdg-desktop-portal which needs user action and can't be triggered automatically. This is arguably one of the most interesting flatpak security features although not all apps support portals.

The question I'm asking to myself is: If what you explained is really safe (and I've no argument to think differently), what for to have commands to customize jails? To me, it seems a waste of work to protect something that is already protected.
I will do a research. If you have good evidence about that, could you please post a link here? So all community will have the answer before asking questions like mine
Thanks!

**Comment by Erick555** [comment]
> Same result, Access everywhere /home /dev /usr/ /boot /run and more
> It really seems that settings cannot be overridden by the user

As I wrote this access comes through portal. For example try `flatpak run --command=sh org.qownnotes.QOwnNotes --nofilesystem=home --filesystem=~/Note` and look at those paths again (`ls /boot`). This will show what real access app have. What you see in gui comes from portal which runs directly on host outside flatpak which is why you can see everything even if it isn't accessible by app other than file(s) you choose on dialog.

> Just to have an example, I also tested Skype and it's perfectly isolated

Because skype is one of those apps that doesn't support portals however for isolation this is harmful in general (comparison between apps may vary as apps that support portal still may have big sandbox hole like filesystem=home as qownnotes have. Still if you use above override then qownnotes will be 90% more isolated than skype while allowing to export/import any file at the same time.

> The question I'm asking to myself is: If what you explained is really safe (and I've no argument to think differently), what for to have commands to customize jails? To me, it seems a waste of work to protect something that is already protected.

Portals are safe but some apps like qownnotes still make a big sandbox holes like filesystem=home for specific reasons, i.e. for directly accessing existing app data. Where users would store qownotes data? `~/Notes`, `~/Docs`, `~/Work`? Nobody knows which is why it allows to access them all. If the user knows they store files in `~/Notes` then it make sense for them to allow only that one path and discard the rest.

**Comment by nidamanx** [comment]
Thank you very very much for your reply.
I think you gave me some good explanations

>and look at those paths again (ls /boot)

How to? I cannot find way (still) to check those things from terminal (after starting QON).
And I really love this sw. I would like to use it in a very safe way. To see all system exposed, makes me a bit uncomfortable.

>Skype is one of those apps that doesn't support portals however for isolation this is harmful in general

I believe you!

>Portals are safe but some apps like qownnotes still make a big sandbox holes like filesystem=home for specific reasons, i.e. for directly accessing existing app data. Where users would store qownotes data?

I agree with you 110%. Even more!
Still, I'm missing why those settings cannot be overridden by the user.

Thanks again!

**Comment by nidamanx** [comment]
Here I am.
Thanks to a friend, I did some more detailed tests.
I admit the use of portal was really a good choice. Now all is fine.

**From portal all is visible, but only from portal.**

Sadly, that visibility triggered my alert bell. 
Thanks for your time, for your excellent work and let's hope this post will help people with their alert bell.
